### ISSUE TITLE
对您的一篇文章有疑问，来请教一下

### ISSUE THREAD

**Issue by oknixus** [pengbotao/itopic.go#2]
http://itopic.org/php-clone.html
尝试了两种方式，发现clone效果和unserialize的效果是完全一样的，这样，您说的，clone是浅复制是不是有问题呢？
```
class Resume
{
    public $height;
}

$ResumeA = new Resume();
$ResumeA->height = 100;
$ResumeB = $ResumeA;
$ResumeB->height = 200;
echo $ResumeA->height;

$ResumeC = clone $ResumeA;
$ResumeC->height = 300;
echo "\n", $ResumeA->height;

$ResumeD = unserialize(serialize($ResumeA));
$ResumeD->height = 400;
echo "\n", $ResumeA->height;
```
结果是：
```
200
200
200
```
效果是一样的，为什么clone是浅复制，而unserialize(serialize(object))却是深复制？
是我理解有问题吗？
求指点，谢谢！

**Comment by pengbotao** [comment]
@oknixus 这个复制或者拷贝深浅有层级的概念在里面，比如`$Resume->workExperience->company`，每一层都是对象。说他是浅拷贝是说是他只拷贝到了第一层。
上面成员属性`$height`的类型是数值类型， 但如果对象`Resume`里另外一个成员属性是一个对象，调用了另一个对象，这个时候`clone`就还是被拷贝对象里的引用。

**Comment by oknixus** [comment]
@pengbotao 谢谢指点😀
