### ISSUE TITLE
用了你的代码过来表示感谢

### ISSUE THREAD

**Issue by jiftle** [pengbotao/itopic.go#4]
一直都想找个这样的博客平台，无奈从0开始太难。偶遇到你的博客非常惊艳，本想go clone下来但是没成功，于是在你的代码基础上造了个新轮子。

附上仓库地址：
[gitmdblog仓库](https://github.com/jiftle/gitmdblog)

**Comment by pengbotao** [comment]
@jiftle  能帮到一点就好，其实博客这东西贵在坚持，养成习惯应该还是会有一点用。
